add missing FTW_ macros for musl
This is to avoid build failures like below for musl.

  locale-util.c:296:24: error: 'FTW_STOP' undeclared

Upstream-Status: Pending

Signed-off-by: Chen Qi <Qi.Chen@windriver.com>